### ISSUE TITLE
[E2E Test 24.08] Edit Certificate Details - No Edit Functionality in Menu

### ISSUE THREAD

**Issue by ds-hzimmer** [eclipse-tractusx/portal-frontend#963] opened 2024-07-24 09:13 UTC
### Current Behavior
An uploaded certificate is visible in user menu "Company Certificates". 
"View" and "Delete" buttons are available here. The processes triggered by those buttons are successful.
First issue: But no "Edit" button/functionality is available here. Thus either a bug, or an already existing test case for a not yet implemented feature?

![Company Certificates - Overview 2](https://github.com/user-attachments/assets/e4f3b68c-ece5-4576-9c31-c86676f9f6b3)

Potential second issue: Uploaded certificates not visible at all in the alternative user menu "Config - Certificates"
![Company Certificates - no uploaded certificates visible](https://github.com/user-attachments/assets/6570962c-63e2-4e88-ad17-d5f548051ea4)

### Expected Behavior
According to the E2E test case "CPLP-3784 / CXTM-254 Edit Certificate Details", an edit functionality to update certificate details (name, exiration date, description) would be expected.

### Steps To Reproduce

Tested in deployed version for release 24.08 (2.1.0-RC2)

Log into Portal (tested with company "Testmanagement")
In menu "Compay Certificates", upload one or multiple certificates, e.g. ISO 9001: successful
View vertificate in menu "Company Certificates": successful
View certificate in menu "Config Certificates": not succesful
Try to edit e.g. the expiration date: not successful/possible

**Comment by evegufy** [comment] 2024-07-24 11:21
Hi @oyo could you please check if an implementation for updating certificate details is even available?
I assume the availability of a test case is misleading, as I don't think the feature even was implemented.

@ds-hzimmer could you please remove the linkt to Jira from the description as it's linking to a closed system, it not friendly to the open community.

**Comment by evegufy** [comment] 2024-07-24 13:05
@ds-hzimmer I suggest to close this issue, as it's not a bug but a missing functionality

@MaximilianHauer could you please clarify if the functionality is part of the roadmap and why a test case was sent to testmanagement when the functionality isn't implemented?

**Closed as not planned** 2024-07-26 13:39 UTC
Labels: bug
